# 网络设备认证配置
# 格式：厂商=用户名,密码

# 默认配置（所有未单独配置的厂商使用此配置）
default=check.sd,ENC:gAAAAABp8yKM8o785C2zvjI3isH8Eju1ym3qgvpPQNKW58YD2AIB4lOf0JWX9QjMZU140Vri5i7m4Vf3L3QpO-psA5F_npql8g==

# 各厂商专用配置（可选）
ruijie=check.sd,ENC:gAAAAABp8yKMFrjOdF6BW8aQJK3IPBw3GvCpwL6ByLUAiMlpdCyYAbdJcowfP4LFPY5NRTTbldMTLwyfoonqMzoJZBo2TGqVzQ==
huawei=check.sd,ENC:gAAAAABp8yKMSUoWrUQ4jCocsrmDodf2gHjsoGNde8C-_NKqHDU7bMq6V8PF6OPHy5Rfrynyu6Fo0W4zFQumjrkfdBZeCE3EvQ==
h3c=check.sd,ENC:gAAAAABp8yKM97Usy1hputto3hcuuTzgupLpafLmVBTQpu8alBWkem2DHHNyr3WG6vae73YPLY4a7KqJh2aTu_n5qSAOcAasfQ==
maipu=check.sd,ENC:gAAAAABp8yKM3RWOdZuwDQKDaMcABSm5-Xtdo0ABHlymP-eDR5JPzVpSB0QQtOQNIaSOkK0yGou8O5kJvaI4YrLEK7hVbjKNaA==
cisco=check.sd,ENC:gAAAAABp8yKMlleLVWpyqtzIK8DMjM7Ij8VSMEJljRm4YFiP_hzVAsVt4yq02CR0FPjOGFFp4pnsyA45dXh4xG1OZGIRKljv-g==
wst=check.sd,ENC:gAAAAABp8yKM8r72KkWkJyARx5uGq3FmIfzBdcCx0ys-djkdaSCsib_fsz0fL1sL7wpP2npVph8atgaNTNXHLkkkvvJ0p0tw5w==
